usecase: wordcount

# kafka
bootstrapServers: "localhost:9092"
schemaRegistryUrl: "http://localhost:8081"

inputTopic: "streams-plaintext-input"
outputTopic: "streams-wordcount-output"

appId: wordcount
