usecase: producer_wordcount

# kafka
bootstrapServers: "localhost:9092"
schemaRegistryUrl: "http://localhost:8081"

appId: producer_wordcount
# topics
inputTopic: "streams-plaintext-input"

produceEventCount: 10