usecase: producer_movies

# kafka
bootstrapServers: "localhost:9092"
schemaRegistryUrl: "http://localhost:8081"

appId: producer_movies
# topics
inputTopic: "streams-movies-input"

schemas:
  - "/home/ansible/Github/kafka-streams/kstreamApp/scripts/movies/movies.avsc"

produceEventCount: 10